### ISSUE TITLE
Investigate package dependecies

### ISSUE THREAD

**Issue by lucasmoura** [TCC-AppRecommender/AppRecommender#1]
Since the project is from 2012, it will be good to investigate which dependencies are still working and the ones that are not.

**Comment by LucianoPC** [comment]
Verificar se o pacote ainda existe no jessie
Se não existir, verificar se não foi renomeado
Verificar o impacto desse pacote no projeto
Buscar possível substituto
No pior caso, adotar o pacote (app-install-data)

**Comment by LucianoPC** [comment]
O app-install-data é um pacote com dados e imagens para instalação com interface gráfica, como o software-center, e geralmente usado pelo adept-installer e gnome-app-install.

https://packages.debian.org/wheezy/app-install-data
http://community.linuxmint.com/software/view/app-install-data

**Comment by lucasmoura** [comment]
Como esse é o único pacote que ainda não esta incluindo nas versões mais recentes do debian, acredito que a questão de dependências esteja resolvida.
