### ISSUE TITLE
Investigar dados usados no projeto

### ISSUE THREAD

**Issue by lucasmoura** [TCC-AppRecommender/AppRecommender#2]
Investigate how the data being used in the project has changed and if the way to collect them has changed as well.

**Comment by lucasmoura** [comment]
O Debian Data Export está fora do ar. Vai ser necessário investigar o impacto disso no projeto. Vai ser necessário começar a considerar talvez outras fontes de dado para o projeto.

**Comment by LucianoPC** [comment]
O Debian Data Export também funciona offline, no site do debian há um exemplo de como usá-lo, segue o link do site:
https://wiki.debian.org/DDE/Tutorial

**Comment by lucasmoura** [comment]
Na pasta src/bin/example, existe uma lista de arquivos que talvez podemos usar de exemplo. Tem um arquivo de submissão do popcon e algumas listas de pacotes.

**Comment by lucasmoura** [comment]
Aparetemente, alguns dos dados que precisamos podem ser gerados via script fornecidos no diretório src/bin. Precisamos só investigar o papel de cada um.

**Comment by lucasmoura** [comment]
Acredito que já possuímos conhecimento dos dados usados no projeto. Considerando o problema relacionado ao DDE e talvez a dificuldade de obter dados do popcon, novas fontes de dados podem ser levantadas para o projeto. Mas para isso, será melhor consultar a comunidade debian.
