### ISSUE TITLE
Criar script para classificar o pacote pelo tempo

### ISSUE THREAD

**Issue by LucianoPC** [TCC-AppRecommender/AppRecommender#25]
- ver a documentação user/share/doc/popularity-contest README.gz
- Estudar como o comando 'stat' funciona

**Comment by LucianoPC** [comment]
Carregar todos os pacotes do usuário no seguinte template:

[nome do pacote] [tempo que foi instalado] [ultimo tempo de acesso]

**Comment by lucasmoura** [comment]
A tarefa foi concluída.
