### ISSUE TITLE
Entrar em contato com packagekit

### ISSUE THREAD

**Issue by LucianoPC** [TCC-AppRecommender/AppRecommender#67]

**Comment by lucasmoura** [comment]
- Packagekit: https://github.com/hughsie/PackageKit
- AppStream: https://github.com/ximion/appstream

**Comment by lucasmoura** [comment]
Enviei o email para a lista do PackageKit, esperando por respostas agora

**Comment by lucasmoura** [comment]
Conversa iniciada, entretanto ainda não cheguei num consenso da melhor abordagem a ser seguida.

**Comment by lucasmoura** [comment]
Acredito que o contanto inicial já foi realizado, e um caminho inicial foi definido para o trabalho.
