### ISSUE TITLE
Procurar artigos sobre importancia da recomendação

### ISSUE THREAD

**Issue by LucianoPC** [TCC-AppRecommender/AppRecommender#9]

**Comment by lucasmoura** [comment]
Primeira fonte de dados que encontrei foi o livro:

Recommender Systems Handbook

O livro é bastante completo no que tange aspectos de recomendação, além de possuir também links para outros artigos que podem ser tornar interessantes para o nosso trabalho. Acabei de terminar o primeiro capítulo. Sendo assim, conforme avançar no livro, vou colocar links de artigos relacionados que achei interessante.

Entretanto, é bom dizer que o terceiro capítulo do livro trata diretamente de recomendações baseada em conteúdo, o que pode já nos guiar em algumas questões.
